source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.1.5'
gem 'pg'
gem 'json'
gem 'nokogiri'
gem 'haml'
gem 'bcrypt-ruby'
gem 'geocoder'
gem 'bootstrap_form'
gem 'kaminari'
gem 'simple_calendar'
gem 'instagram'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'koala'
gem 'twitter'
gem 'omniauth-twitter'
gem 'tumblr_client'
gem 'omniauth-tumblr'
gem "omniauth-google-oauth2"
gem 'rest-client'
gem 'chartkick'
gem 'exception_notification'

group :development do
  gem 'sqlite3'
  gem 'awesome_print'
  gem 'pry'
end
